# nfty - internal/lan host
# good starting point for home servers, Pis, etc.
## example: pihole DNS + small web UI + SNMP polling.
# -------------------------------------------------------------------

[core]
  name          = "my-host-firewall"
  description   = "Internal node - pihole DNS & web UI + SNMP monitoring"
  table         = "nfty-default"
  docker_compat = false
  persist       = true
  default_rules = true
  icmp_limit    = "10/s"
  log_ssh_fails = true  # any box running DNS should not be exposed to the public internet anyway!

[chains.policy]
  input       = "drop"
  forward     = "drop"
  output      = "accept"
  postrouting = "accept"

# ---------------------------------------------------------------------------
# IP Lists
# ---------------------------------------------------------------------------

[lists.ipv4.ssh]
  comment = "SSH allowlist"
  entries = [
    "10.100.1.5/32", # desktop
  ]

[lists.ipv4.webui]
  comment = "Web UI allowlist"
  entries = [
    "10.100.1.0/24", # home subnet
    "172.16.1.0/24", # vpn subnet
  ]

[lists.ipv4.dns]
  comment = "DNS allowlist - keep restricted"
  entries = [
    "10.100.1.0/24",
    "172.16.1.0/24",
  ]

[lists.ipv4.snmp]
  comment = "SNMP for monitoring"
  entries = [
    "172.16.1.5/32", # NMS server
  ]

# important to keep this one tightened if using IPv6 on your LAN
# as most IPv6 addresses are publicly routeable, and function as public IPs!
[lists.ipv6.dns]
  comment = "IPv6 DNS allowlist"
  entries = [
    "2001:db8::/64",
    "2001:db8::2/128",
  ]

# ---------------------------------------------------------------------------
# IPv4 INPUT
# ---------------------------------------------------------------------------

[[chains.ipv4.input]]
  comment  = "SSH"
  protocol = "tcp"
  dport    = [22]
  src_list = "ssh"
  action   = "accept"

[[chains.ipv4.input]]
  comment  = "Pihole web UI"
  protocol = "tcp"
  dport    = [80, 443]
  src_list = "webui"
  action   = "accept"

# Can define multiple protocols in one rule, useful for things like DNS which use both tcp and udp
[[chains.ipv4.input]]
  comment  = "DNS - tcp + udp"
  protocol = ["tcp", "udp"]
  dport    = [53]
  src_list = "dns"
  action   = "accept"

# If you use any sort of NMS
[[chains.ipv4.input]]
  comment  = "SNMP polling"
  protocol = "udp"
  dport    = [161]
  src_list = "snmp"
  action   = "accept"

# ---------------------------------------------------------------------------
# IPv6 INPUT
# ---------------------------------------------------------------------------

[[chains.ipv6.input]]
  comment  = "DNS IPv6 - keep srclist tight"
  protocol = ["tcp", "udp"]
  dport    = [53]
  src_list = "dns"
  action   = "accept"